source 'https://github.com/CocoaPods/Specs.git'

target 'Voltron' do
  pod "Voltron", :path => "../"
end

target 'Tests' do
  pod "Voltron", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
